### PR TITLE
change "not using geodes provided systems" rule to include web requests

### PR DESCRIPTION
**Pull request by Capeling**

### CODE REVIEW

**Comment by matcool** [comment]
y

**Comment by hiimjustin000** [comment]
there are mods in pending that use winapi to send raw http requests

**Comment by matcool** [comment]
using a different library for web requests does not cause mod incompatibility in any way, so its not a good reason to reject a mod imo

**Comment by HJfod** [comment]
I was going to add this in my last rule change but decided against it because
1. It doesn't support more advanved features like WebSockets, so there can be good reason to roll your own networking lib
2. It doesn't pose mod incompatability concerns (aside from GDIntercept which is not a good enough reason imo)
Using bad techniques is fair as long as your mod works. Of course if they do result in bugs, there is a rule that mods with a ton of frequent unfixed bugs may be delisted if the developer does nothing to address them

**Pull request closed without merging**
